/*
 * This file is generated by jOOQ.
 */
package victor.training.spring.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import victor.training.spring.jooq.tables.Comment;
import victor.training.spring.jooq.tables.Post;
import victor.training.spring.jooq.tables.records.CommentRecord;
import victor.training.spring.jooq.tables.records.PostRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CommentRecord> COMMENT_PKEY = Internal.createUniqueKey(Comment.COMMENT, DSL.name("comment_pkey"), new TableField[] { Comment.COMMENT.ID }, true);
    public static final UniqueKey<PostRecord> POST_PKEY = Internal.createUniqueKey(Post.POST, DSL.name("post_pkey"), new TableField[] { Post.POST.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CommentRecord, PostRecord> COMMENT__FKS1SLVNKUEMJSQ2KJ4H3VHX7I1 = Internal.createForeignKey(Comment.COMMENT, DSL.name("fks1slvnkuemjsq2kj4h3vhx7i1"), new TableField[] { Comment.COMMENT.POST_ID }, Keys.POST_PKEY, new TableField[] { Post.POST.ID }, true);
}
