/*
 * This file is generated by jOOQ.
 */
package victor.training.spring.flux.jooq;


import victor.training.spring.flux.jooq.tables.Comment;
import victor.training.spring.flux.jooq.tables.Post;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.comment</code>.
     */
    public static final Comment COMMENT = Comment.COMMENT;

    /**
     * The table <code>public.post</code>.
     */
    public static final Post POST = Post.POST;
}
